"""Preprocess raw single-patient fiber data into a ground truth, prior mean, and synthetic
activation-time observations for the fiber-orientation inverse problem.

`--data-dir` is required and never assumed, so the same script drives simulation studies over many
parameterizations, each pointed at its own data directory. Run
`pixi run python scripts/preprocess_data.py --help` for the full option list, or
`pixi run preprocess -- --data-dir <dir>` via the pixi task.

The ground truth comes from exactly one `GroundTruthStrategy`, chosen via `--ground-truth`:
`real-data-ground-truth-strategy` (default, derived from the patient's raw fiber data) or
`synthetic-ground-truth-strategy` (sampled from the SPDE prior itself; see
`preprocessing.ground_truth`'s docstring). Its prior mean is computed uniformly afterward,
the same way regardless of strategy. Synthetic observations are always generated by forward-solving
whichever ground truth was chosen, through an eikonal forward map that interpolates the vertex-based
angle field onto simplices via exactly one `InterpolationStrategy`, chosen via `--interpolation`:
`nearest-neighbor-interpolation-strategy` (default, takes the value at the vertex nearest each
triangle's centroid) or `linear-interpolation-strategy` (averages a triangle's three vertex
values); see `mesh.interpolation`'s docstring.

Everything the script reports (start time, command line, settings, progress steps, summaries) is
also logged to `--run-logfile-path` (default `<data_dir>/logs/preprocess_data.log`, overwritten on
every run), so the settings are stored with the run.

To regenerate `example_data/preprocessing/` from
`example_data/raw/{mesh.vtu,fiber_field.npy,basis_vecs.npy}` with the reference settings below:

    pixi run python scripts/preprocess_data.py --data-dir example_data
"""

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import tyro
from ls_bayesian.common.logging import BaseLogger

from bayes_cep.mesh.interpolation import (
    LinearInterpolationStrategy,
    NearestNeighborInterpolationStrategy,
)
from bayes_cep.mesh.io import load_pyvista_mesh
from bayes_cep.posterior.eikonal_map import EikonalParameterToSolutionMap, EikonalSolverSettings
from bayes_cep.preprocessing.ground_truth import (
    RealDataGroundTruthStrategy,
    SyntheticGroundTruthStrategy,
)
from bayes_cep.preprocessing.prior_mean import build_constant_prior_mean
from bayes_cep.preprocessing.synthetic_observations import (
    ObservationSamplingSettings,
    generate_synthetic_observations,
)
from bayes_cep.reporting.console import (
    describe_array,
    report_step,
    resolve_logfile_path,
    run_logger,
)

# Reference settings, reproduced from the legacy single-patient MAP study (`application/map.ipynb`/
# `application/prior.ipynb` in the cardiac-electrophysiology repo). Used only as
# `PreprocessingSettings` defaults below; every one of them is overridable on the command line.
REFERENCE_INITIAL_SITE_IND = 12650
REFERENCE_LONGITUDINAL_VELOCITY = 1.5
REFERENCE_TRANSVERSAL_VELOCITY = 1.0
REFERENCE_NUM_OBSERVATIONS = 1000
REFERENCE_NOISE_VARIANCE = 1e-3
REFERENCE_OBSERVATION_SEED = 0


# ==================================================================================================
@dataclass(frozen=True)
class PreprocessingSettings:
    """Settings for `preprocess_data.py`.

    Only `data_dir` has no default: every other field is a reference scientific setting (reproduced
    from the legacy single-patient MAP study), while the data location itself must always be given
    explicitly rather than assumed.

    Attributes:
        data_dir (Path): Directory containing a `raw/` subfolder with `mesh.vtu`, `fiber_field.npy`,
            `basis_vecs.npy`. Outputs are written to `<data_dir>/preprocessing/`.
        eikonal (EikonalSolverSettings): Eikonal forward-solver settings, used both for the
            ground truth's forward solve and for the synthetic observations.
        observations (ObservationSamplingSettings): Synthetic activation-time observation settings.
        ground_truth (RealDataGroundTruthStrategy | SyntheticGroundTruthStrategy): Strategy
            producing the ground-truth angle field; defaults to the real-data strategy. Selected on
            the command line via `--ground-truth:<strategy-name>`. Its constant prior mean is
            computed uniformly afterward, the same way regardless of strategy.
        interpolation (LinearInterpolationStrategy | NearestNeighborInterpolationStrategy): Strategy
            interpolating the vertex-based angle field onto simplices for the eikonal forward map
            used to generate synthetic observations; defaults to nearest-neighbor interpolation.
            Selected on the command line via `--interpolation:<strategy-name>`.
        run_logfile_path (Path | None): File the script's output (settings, progress, summaries) is
            logged to in addition to the console, so the settings are stored with the run. A
            relative path is resolved against `data_dir`; defaults to `logs/preprocess_data.log`.
            Overwritten on every run; pass `None` to disable.
    """

    data_dir: Path
    eikonal: EikonalSolverSettings = field(
        default_factory=lambda: EikonalSolverSettings(
            initial_site_ind=REFERENCE_INITIAL_SITE_IND,
            longitudinal_velocity=REFERENCE_LONGITUDINAL_VELOCITY,
            transversal_velocity=REFERENCE_TRANSVERSAL_VELOCITY,
        )
    )
    observations: ObservationSamplingSettings = field(
        default_factory=lambda: ObservationSamplingSettings(
            num_observations=REFERENCE_NUM_OBSERVATIONS,
            noise_variance=REFERENCE_NOISE_VARIANCE,
            seed=REFERENCE_OBSERVATION_SEED,
        )
    )
    ground_truth: RealDataGroundTruthStrategy | SyntheticGroundTruthStrategy = field(
        default_factory=SyntheticGroundTruthStrategy
    )
    interpolation: LinearInterpolationStrategy | NearestNeighborInterpolationStrategy = field(
        default_factory=NearestNeighborInterpolationStrategy
    )
    run_logfile_path: Path | None = Path("logs/preprocess_data.log")


# ==================================================================================================
def main(settings: PreprocessingSettings) -> None:
    """Run the preprocessing pipeline, logging its output to `settings.run_logfile_path`."""
    with run_logger(resolve_logfile_path(settings.data_dir, settings.run_logfile_path)) as logger:
        _run(settings, logger)


# ==================================================================================================
def _run(settings: PreprocessingSettings, logger: BaseLogger) -> None:
    """Build the ground truth, prior mean, and observations, cache to `<data_dir>/preprocessing`."""
    raw_dir = settings.data_dir / "raw"
    preprocessing_dir = settings.data_dir / "preprocessing"
    num_steps = 5

    logger.info("Preprocessing settings")
    logger.info(f"  data directory : {settings.data_dir}")
    logger.info(f"  ground truth   : {settings.ground_truth}")
    logger.info(f"  interpolation  : {settings.interpolation}")
    logger.info(f"  eikonal solver : {settings.eikonal}")
    logger.info(f"  observations   : {settings.observations}")
    logger.info("")

    with report_step(logger, 1, num_steps, f"Loading raw data from {raw_dir}"):
        mesh = load_pyvista_mesh(raw_dir / "mesh.vtu")
        fiber_field = np.load(raw_dir / "fiber_field.npy")
        basis_vectors = np.load(raw_dir / "basis_vecs.npy")
    logger.info(f"      mesh: {mesh.n_points} vertices, {mesh.n_cells} triangles")

    strategy_name = type(settings.ground_truth).__name__
    with report_step(logger, 2, num_steps, f"Building ground-truth angle field ({strategy_name})"):
        ground_truth_angle_field = settings.ground_truth.build(mesh, fiber_field, basis_vectors)
    logger.info(f"      {describe_array('ground truth [rad]', ground_truth_angle_field)}")

    with report_step(logger, 3, num_steps, "Computing constant prior mean from the ground truth"):
        prior_mean_angle_field = build_constant_prior_mean(ground_truth_angle_field)
    logger.info(f"      prior mean angle: {prior_mean_angle_field[0]:.4f} rad")

    interpolation_name = type(settings.interpolation).__name__
    with report_step(
        logger,
        4,
        num_steps,
        f"Generating synthetic observations ({interpolation_name} forward map)",
    ):
        forward_map = EikonalParameterToSolutionMap(
            mesh, basis_vectors, settings.eikonal, settings.interpolation
        )
        observed_vertex_indices, observed_activation_times = generate_synthetic_observations(
            forward_map, ground_truth_angle_field, settings.observations
        )
    logger.info(f"      observed {observed_vertex_indices.shape[0]} of {mesh.n_points} vertices")
    logger.info(f"      {describe_array('noisy activation times', observed_activation_times)}")

    outputs = {
        "ground_truth_angle_field.npy": ground_truth_angle_field,
        "prior_mean_angle_field.npy": prior_mean_angle_field,
        "observed_vertex_indices.npy": observed_vertex_indices,
        "observed_activation_times.npy": observed_activation_times,
    }
    with report_step(logger, 5, num_steps, f"Writing outputs to {preprocessing_dir}"):
        preprocessing_dir.mkdir(exist_ok=True)
        for filename, array in outputs.items():
            np.save(preprocessing_dir / filename, array)
    for filename, array in outputs.items():
        logger.info(f"      {filename} {array.shape} {array.dtype}")
    logger.info("Preprocessing finished.")


if __name__ == "__main__":
    main(tyro.cli(PreprocessingSettings))
